# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:
    include:
      - release
    exclude:
      - develop
      - master
      - feature*
      - hotfix

pool:
  vmImage: 'windows-latest'

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud-test'
      organization: 'hergoln-test-key'
      scannerMode: 'Other'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      goals: 'package'

# according to https://sonarcloud.io/documentation/analysis/scan/sonarscanner-for-azure-devops/
# this one works only for release pipelines on AzureDevOps apparently :/
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'